[global]
   workgroup = WORKGROUP
   server string = diegofnunesbr
   security = user
   map to guest = never
   log file = /dev/stdout
   max log size = 0
   load printers = no
   printcap name = /dev/null
   disable spoolss = yes

[diegofnunesbr]
   path = /data
   browseable = yes
   read only = no
   valid users = diegofnunesbr
   force user = root
   force group = root
