apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: samba
  labels:
    app: samba
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: samba
          image: samba/server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SMB_USER
              value: diegofnunesbr
            - name: SMB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: samba-secrets
                  key: smb-password
          volumeMounts:
            - name: data
              mountPath: /data
            - name: samba-config
              mountPath: /var/lib/samba
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
      volumes:
        - name: data
          hostPath:
            path: /diegofnunesbr
            type: Directory
        - name: samba-config
          hostPath:
            path: /var/lib/samba-config
            type: Directory
