---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: samba-secrets
  namespace: samba
spec:
  encryptedData:
    smb-password: AgBNgFlCUxvCkTp7iDYwA1soFYWMLHqVUndAy0gV3KmHnLDSK2uJOycYrGFoGXHW3uw0jhWbvUB4HdD0Ekwh8jTzu/P5b0haL+6Y3gzDqWQEBxCOewg2iGJYmIsm59+OIeAfs4yvP6n83L31UFvpqoqiojP/fw0fodA4kAUgaKfEklyoEHYLy8g/zCutMdlU2cAS2trQC7PktDSBmXhFcvrhvaV233T3sxeDOIKtPABOd0z+/z8TbfUUhmTyPNaT3n3jogos4NbLQav+BE21nXS/28ANBIxWs+t68U7PJdR1DPQO2yLpDp4PV9vw7FWazsjOMIiSWSXqQLyLTsAADc12k8Q2CCmwWs8gs850aaYGal1t26VBujaYpILPQktAlty4zwoh2tX59djR0bQsRA7Ydclh7DE5zlGEpv/1CQCebZ9dSEndhc/G2BvXHaY2U7WMGVw0DocRiHyfvdQgNngTldHENRQLwcvRJTGBQ1sGa/Ee1yytmgPLez5ZNWX/pAJQHOHLnxiI086TKuX+/jYh6cLaR019Lu3zCzzyVBmqXKLKizR5toiKT3He0wAPxyoHNzLku004npMh11tzxvgHtX003WyImQzaDDoKIB87RoqjrW35BDBv3gZDNiiUIHDqzpRhndP1JsStf3e3+l4FfoKJ3EcsTL+Zfl3cQrH+vhcHugeeMgfxM5oQfvOiJk4hwVSdFhP9jjaqks11JO2Bvvlvsd47Nh3Ffy6ahvpHuw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: samba-secrets
      namespace: samba
    type: Opaque
