---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: samba-secrets
  namespace: samba
spec:
  encryptedData:
    smb-password: AgAGBXrVrF3nN+sIRj+lJD5sixDCxtuj8Y6IApAdlTj9Fdcgq1j2bIHPvw+J/4sqFpVIAeGEUpUKNWtBhENbLmauYl3wzVvZooGJAsxEktPSreys1+J16MnAJPAQ6Vgs0CI8dNAtlX+iWHix+j72RjhzNCemcfuO/y7154VahL82wUoIWPQ1oOVeVEautI9U5CXGpICZnZjxJiKD9t1kG/6HeF6dNHBgnrpVh+JqLOQusKgg1KtQyTXxeIBs/n0AweT3lgAFi0nt18Pi18QpEsRXCxYJK3ZE6nZrC8ePweNwGw2bmBKzjb8nKXdXHIoXXPQQ7o7mKJLWjwm7E/Ijr5r4PlEqkgxXFowN7f0QzPbwhcg4wE6do2KooJpkBDqk4nWhVtV0Mtu64vba6vJM7ZImuYGDsAFVj1jNCDSMgwYp4OO0L10a/kztn0J3aHFBxC3BeBInKm+KT+cpWAKQ4/UkjXmYP0kYzwad+VY2FyfFPFGiq+t7Zqxvy+bkAx2dHE5hQVyLnNGK2hGQNgy9zk2nTvAgMC5K/f02QxiWlTzzwqou7CU1kUZGYeQmeem7qW6r75EFygpvrsN3Nx+JFmM6KT40iepEGqZQyP23NmNanWry4Ea+vM+ixs8r2SgHsyvUbSpfw1q6feBtKlNp5iJwHaPE4sEkEqbBGRgmS36QyUh0eB0///CBqTQPbWrT9xrNGHYn6Bc5GK5YqQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: samba-secrets
      namespace: samba
    type: Opaque
